version: "3.1"

services:
  api:
    image: "${REGISTRY}/api:${ENV}"
    container_name: api
    restart: always
    build:
      context: api
      dockerfile: api.Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - tinypage

#  editor:
#    image: registry.digitalocean.com/tinypage/editor:latest
#    build:
#      context: editor
#      dockerfile: editor.Dockerfile
#    depends_on:
#      - api
#    ports:
#      - "3333:80"
#    networks:
#      - singlelink
#
#  renderer:
#    image: registry.digitalocean.com/tinypage/renderer:latest
#    build:
#      context: renderer
#      dockerfile: renderer.Dockerfile
#    depends_on:
#      - api
#    ports:
#      - "3000:80"
#    networks:
#      - singlelink

networks:
  tinypage:
